// Package astp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package astp

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/mr-pmillz/gophlare/flareapi/flaretime"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthDomainQueryType.
const (
	AuthDomain AuthDomainQueryType = "auth_domain"
)

// Valid indicates whether the value is a known member of the AuthDomainQueryType enum.
func (e AuthDomainQueryType) Valid() bool {
	switch e {
	case AuthDomain:
		return true
	default:
		return false
	}
}

// Defines values for CredentialsInclude.
const (
	AuthDomains     CredentialsInclude = "auth_domains"
	KnownPasswordID CredentialsInclude = "known_password_id"
	Urls            CredentialsInclude = "urls"
)

// Valid indicates whether the value is a known member of the CredentialsInclude enum.
func (e CredentialsInclude) Valid() bool {
	switch e {
	case AuthDomains:
		return true
	case KnownPasswordID:
		return true
	case Urls:
		return true
	default:
		return false
	}
}

// Defines values for DomainQueryType.
const (
	Domain DomainQueryType = "domain"
)

// Valid indicates whether the value is a known member of the DomainQueryType enum.
func (e DomainQueryType) Valid() bool {
	switch e {
	case Domain:
		return true
	default:
		return false
	}
}

// Defines values for EmailQueryType.
const (
	Email EmailQueryType = "email"
)

// Valid indicates whether the value is a known member of the EmailQueryType enum.
func (e EmailQueryType) Valid() bool {
	switch e {
	case Email:
		return true
	default:
		return false
	}
}

// Defines values for KeywordQueryType.
const (
	Keyword KeywordQueryType = "keyword"
)

// Valid indicates whether the value is a known member of the KeywordQueryType enum.
func (e KeywordQueryType) Valid() bool {
	switch e {
	case Keyword:
		return true
	default:
		return false
	}
}

// Defines values for Order.
const (
	Asc  Order = "asc"
	Desc Order = "desc"
)

// Valid indicates whether the value is a known member of the Order enum.
func (e Order) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for SecretQueryType.
const (
	Secret SecretQueryType = "secret"
)

// Valid indicates whether the value is a known member of the SecretQueryType enum.
func (e SecretQueryType) Valid() bool {
	switch e {
	case Secret:
		return true
	default:
		return false
	}
}

// AuthDomainQuery Matches the domain of the service the credential might have been used to log in to.
type AuthDomainQuery struct {
	Fqdn string              `json:"fqdn"`
	Type AuthDomainQueryType `json:"type"`
}

// AuthDomainQueryType defines model for AuthDomainQuery.Type.
type AuthDomainQueryType string

// ByAccountsRequest defines model for ByAccountsRequest.
type ByAccountsRequest struct {
	// Accounts The exact account names to look up. Wildcard and domain searches are not supported.
	Accounts []string `json:"accounts"`
}

// ByAccountsResponse The identity for each requested account, keyed by account name.
type ByAccountsResponse map[string]Identity

// Cookie defines model for Cookie.
type Cookie struct {
	Domain string `json:"domain,omitempty,omitzero"`

	// EventUID UID of the stealer log event the cookie was leaked in.
	EventUID  string         `json:"event_uid,omitempty,omitzero"`
	ExpiresAt flaretime.Time `json:"expires_at,omitempty,omitzero"`

	// ImportedAt When the cookie was imported to Flare's database.
	ImportedAt flaretime.Time `json:"imported_at,omitempty,omitzero"`
	Name       string         `json:"name,omitempty,omitzero"`
	Path       string         `json:"path,omitempty,omitzero"`

	// UUID Uniquely identifies the cookie.
	UUID  string `json:"uuid,omitempty,omitzero"`
	Value string `json:"value,omitempty,omitzero"`
}

// CookiesSearchRequest defines model for CookiesSearchRequest.
type CookiesSearchRequest struct {
	// Domain The exact domain to search cookies for. Subdomains are not included.
	Domain string `json:"domain,omitempty,omitzero"`

	// ExpiresAfter Only return cookies that expire after this time.
	ExpiresAfter flaretime.Time `json:"expires_after,omitempty,omitzero"`

	// From The next value from the last response.
	From string `json:"from,omitempty,omitzero"`

	// ImportedAfter Only return cookies added to Flare's database after this time.
	ImportedAfter flaretime.Time `json:"imported_after,omitempty,omitzero"`

	// Names Cookie names to filter for, for example session or PHPSESSID.
	Names []string `json:"names,omitempty,omitzero"`
	Order Order    `json:"order,omitempty,omitzero"`

	// Paths Cookie paths to filter for, for example / or /login.
	Paths []string `json:"paths,omitempty,omitzero"`

	// Size The number of results to fetch (default 100, maximum 2000).
	Size int `json:"size,omitempty,omitzero"`

	// Values Exact cookie values to search for. Currently limited to a single value.
	Values []string `json:"values,omitempty,omitzero"`
}

// CookiesSearchResponse defines model for CookiesSearchResponse.
type CookiesSearchResponse struct {
	Items []Cookie `json:"items"`
	Next  string   `json:"next,omitempty,omitzero"`
}

// Credential defines model for Credential.
type Credential struct {
	// AuthDomains Only returned when include contains auth_domains.
	AuthDomains    []string `json:"auth_domains,omitempty,omitzero"`
	CredentialHash string   `json:"credential_hash"`
	Domain         string   `json:"domain"`
	EventUID       string   `json:"event_uid"`

	// Hash The leaked secret. Flare does not distinguish plaintext passwords from hashes.
	Hash         string         `json:"hash"`
	HashType     string         `json:"hash_type"`
	ID           int64          `json:"id"`
	IdentityName string         `json:"identity_name"`
	ImportedAt   flaretime.Time `json:"imported_at"`

	// KnownPasswordID Only returned when include contains known_password_id.
	KnownPasswordID int64            `json:"known_password_id"`
	Source          CredentialSource `json:"source"`
	SourceID        string           `json:"source_id"`

	// Urls Only returned when include contains urls.
	Urls []string `json:"urls,omitempty,omitzero"`
}

// CredentialSource defines model for CredentialSource.
type CredentialSource struct {
	BreachedAt     flaretime.Time `json:"breached_at"`
	DescriptionEn  string         `json:"description_en"`
	DescriptionFr  string         `json:"description_fr"`
	ID             string         `json:"id"`
	IsAlertEnabled bool           `json:"is_alert_enabled"`
	LeakedAt       flaretime.Time `json:"leaked_at"`
	Name           string         `json:"name"`
	PiiTags        []string       `json:"pii_tags,omitempty,omitzero"`
	URL            string         `json:"url,omitempty,omitzero"`
}

// CredentialURL defines model for CredentialURL.
type CredentialURL struct {
	CredentialHash string `json:"credential_hash,omitempty,omitzero"`

	// Domain The URL's host.
	Domain string `json:"domain,omitempty,omitzero"`

	// URL The full URL, including scheme and path.
	URL string `json:"url,omitempty,omitzero"`
}

// CredentialsFilters defines model for CredentialsFilters.
type CredentialsFilters struct {
	ImportedAt DateRangeFilter `json:"imported_at,omitempty,omitzero"`
}

// CredentialsInclude known_password_id returns the ID of the credential's password. auth_domains returns up to 100 hosts where the credential was seen being used. urls returns up to 100 full URLs where the credential was seen being used.
type CredentialsInclude string

// CredentialsQuery defines model for CredentialsQuery.
type CredentialsQuery struct {
	union json.RawMessage
}

// CredentialsSearchRequest defines model for CredentialsSearchRequest.
type CredentialsSearchRequest struct {
	Filters CredentialsFilters `json:"filters,omitempty,omitzero"`

	// From The next value from the last response.
	From string `json:"from,omitempty,omitzero"`

	// Include Additional fields to return.
	Include []CredentialsInclude `json:"include,omitempty,omitzero"`
	Order   Order                `json:"order,omitempty,omitzero"`
	Query   CredentialsQuery     `json:"query"`

	// Size Maximum number of credentials to return (maximum 10 000).
	Size int `json:"size,omitempty,omitzero"`
}

// CredentialsSearchResponse defines model for CredentialsSearchResponse.
type CredentialsSearchResponse struct {
	Items []Credential `json:"items"`

	// Next The from value for the next page; null once every page was viewed.
	Next string `json:"next"`
}

// CredentialsV2Response defines model for CredentialsV2Response.
type CredentialsV2Response struct {
	Items []LeakedCredential `json:"items,omitempty,omitzero"`
	Next  string             `json:"next,omitempty,omitzero"`
}

// DateRangeFilter defines model for DateRangeFilter.
type DateRangeFilter struct {
	// Gte Matches values greater than or equal to the timestamp.
	Gte flaretime.Time `json:"gte,omitempty,omitzero"`

	// Lte Matches values lesser than or equal to the timestamp.
	Lte flaretime.Time `json:"lte,omitempty,omitzero"`
}

// DomainQuery Matches credentials whose email address contains the domain.
type DomainQuery struct {
	Fqdn string          `json:"fqdn"`
	Type DomainQueryType `json:"type"`
}

// DomainQueryType defines model for DomainQuery.Type.
type DomainQueryType string

// EmailQuery Matches credentials for the exact email address.
type EmailQuery struct {
	Email string         `json:"email"`
	Type  EmailQueryType `json:"type"`
}

// EmailQueryType defines model for EmailQuery.Type.
type EmailQueryType string

// Identity defines model for Identity.
type Identity struct {
	Links IdentityLinks `json:"links,omitempty,omitzero"`
	Name  string        `json:"name,omitempty,omitzero"`

	// Passwords Up to 100 passwords, in the order they were inserted into the database.
	Passwords []IdentityPassword `json:"passwords,omitempty,omitzero"`
}

// IdentityLinks defines model for IdentityLinks.
type IdentityLinks struct {
	// Next URL of the identity's next page of passwords, present when it has more than the ones included. Follow it with a valid Authorization token. Flare does not document the URL's form or its response; gophlare accepts an identity object or a list of identities.
	Next                 string                 `json:"next,omitempty,omitzero"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// IdentityList defines model for IdentityList.
type IdentityList = []Identity

// IdentityPassword defines model for IdentityPassword.
type IdentityPassword struct {
	CredentialHash string                 `json:"credential_hash,omitempty,omitzero"`
	Domain         string                 `json:"domain,omitempty,omitzero"`
	Extra          map[string]interface{} `json:"extra,omitempty,omitzero"`

	// Hash The leaked secret. Flare does not distinguish plaintext passwords from hashes.
	Hash       string         `json:"hash,omitempty,omitzero"`
	HashType   string         `json:"hash_type,omitempty,omitzero"`
	ID         int64          `json:"id,omitempty,omitzero"`
	ImportedAt flaretime.Time `json:"imported_at,omitempty,omitzero"`
	Source     LeakSource     `json:"source,omitempty,omitzero"`
	SourceID   string         `json:"source_id,omitempty,omitzero"`

	// SourceParams Undocumented; always null in Flare's examples.
	SourceParams interface{} `json:"source_params,omitempty,omitzero"`
}

// KeywordQuery Matches the part of the identity name before the @.
type KeywordQuery struct {
	Keyword string           `json:"keyword"`
	Type    KeywordQueryType `json:"type"`
}

// KeywordQueryType defines model for KeywordQuery.Type.
type KeywordQueryType string

// LeakSource defines model for LeakSource.
type LeakSource struct {
	BreachedAt      flaretime.Time `json:"breached_at,omitempty,omitzero"`
	Description     string         `json:"description,omitempty,omitzero"`
	DescriptionFr   string         `json:"description_fr,omitempty,omitzero"`
	HashDescription string         `json:"hash_description,omitempty,omitzero"`
	HashType        string         `json:"hash_type,omitempty,omitzero"`
	ID              string         `json:"id,omitempty,omitzero"`
	IsAlertsEnabled bool           `json:"is_alerts_enabled,omitempty,omitzero"`
	LeakedAt        flaretime.Time `json:"leaked_at,omitempty,omitzero"`
	Name            string         `json:"name,omitempty,omitzero"`
	RelatedUrls     []string       `json:"related_urls,omitempty,omitzero"`
	URL             string         `json:"url,omitempty,omitzero"`
}

// LeakedCredential defines model for LeakedCredential.
type LeakedCredential struct {
	CredentialHash string                 `json:"credential_hash,omitempty,omitzero"`
	Domain         string                 `json:"domain,omitempty,omitzero"`
	Extra          map[string]interface{} `json:"extra,omitempty,omitzero"`
	Hash           string                 `json:"hash,omitempty,omitzero"`
	HashType       string                 `json:"hash_type,omitempty,omitzero"`
	ID             int64                  `json:"id,omitempty,omitzero"`
	IdentityName   string                 `json:"identity_name,omitempty,omitzero"`
	ImportedAt     flaretime.Time         `json:"imported_at,omitempty,omitzero"`
	Source         LeakSource             `json:"source,omitempty,omitzero"`
	SourceID       string                 `json:"source_id,omitempty,omitzero"`

	// SourceParams Undocumented; always null in Flare's examples.
	SourceParams interface{} `json:"source_params,omitempty,omitzero"`
}

// Order defines model for Order.
type Order string

// SecretQuery Matches credentials that contain the password.
type SecretQuery struct {
	Secret string          `json:"secret"`
	Type   SecretQueryType `json:"type"`
}

// SecretQueryType defines model for SecretQuery.Type.
type SecretQueryType string

// SourcesResponse defines model for SourcesResponse.
type SourcesResponse struct {
	// Cursors Undocumented; always empty in Flare's examples.
	Cursors    []interface{} `json:"cursors,omitempty,omitzero"`
	Items      []*LeakSource `json:"items,omitempty,omitzero"`
	Next       string        `json:"next,omitempty,omitzero"`
	TotalCount int           `json:"total_count,omitempty,omitzero"`
}

// URLsByCredentialHashRequest defines model for URLsByCredentialHashRequest.
type URLsByCredentialHashRequest struct {
	// CredentialHash A credential_hash returned by the credentials search.
	CredentialHash string `json:"credential_hash"`

	// From The next value from the last response.
	From string `json:"from,omitempty,omitzero"`

	// Size Maximum number of URLs to return (default 100, maximum 5000).
	Size int `json:"size,omitempty,omitzero"`
}

// URLsByCredentialHashResponse defines model for URLsByCredentialHashResponse.
type URLsByCredentialHashResponse struct {
	Items []CredentialURL `json:"items"`
	Next  string          `json:"next"`
}

// CredentialsFeedSize defines model for CredentialsFeedSize.
type CredentialsFeedSize = int

// FeedOrder defines model for FeedOrder.
type FeedOrder = Order

// From defines model for From.
type From = string

// FromID defines model for FromID.
type FromID = int64

// Size defines model for Size.
type Size = int

// SourceID defines model for SourceID.
type SourceID = string

// ListSourcesParams defines parameters for ListSources.
type ListSourcesParams struct {
	// Size Maximum number of results to return (maximum 10 000).
	Size Size `form:"size,omitempty" json:"size,omitempty,omitzero"`

	// From The next value from the last response.
	From From `form:"from,omitempty" json:"from,omitempty,omitzero"`
}

// ListCredentialsV1Params defines parameters for ListCredentialsV1.
type ListCredentialsV1Params struct {
	// Size Maximum number of results to return (maximum 5 000).
	Size CredentialsFeedSize `form:"size,omitempty" json:"size,omitempty,omitzero"`

	// From ID of the entry to start after (exclusive).
	From FromID `form:"from,omitempty" json:"from,omitempty,omitzero"`

	// Order Browse order. Defaults to asc, which is recommended for fetching newly imported passwords.
	Order FeedOrder `form:"order,omitempty" json:"order,omitempty,omitzero"`

	// SourceID Return only credentials that belong to this source.
	SourceID SourceID `form:"source_id,omitempty" json:"source_id,omitempty,omitzero"`
}

// ListByDomainParams defines parameters for ListByDomain.
type ListByDomainParams struct {
	// Size Maximum number of results to return (maximum 10 000).
	Size Size `form:"size,omitempty" json:"size,omitempty,omitzero"`

	// From ID of the entry to start after (exclusive).
	From FromID `form:"from,omitempty" json:"from,omitempty,omitzero"`
}

// ListByKeywordParams defines parameters for ListByKeyword.
type ListByKeywordParams struct {
	// Size Maximum number of results to return (maximum 10 000).
	Size Size `form:"size,omitempty" json:"size,omitempty,omitzero"`

	// From ID of the entry to start after (exclusive).
	From FromID `form:"from,omitempty" json:"from,omitempty,omitzero"`
}

// ListByPasswordParams defines parameters for ListByPassword.
type ListByPasswordParams struct {
	// Size Maximum number of results to return (maximum 10 000).
	Size Size `form:"size,omitempty" json:"size,omitempty,omitzero"`

	// From ID of the entry to start after (exclusive).
	From FromID `form:"from,omitempty" json:"from,omitempty,omitzero"`
}

// ListCredentialsV2Params defines parameters for ListCredentialsV2.
type ListCredentialsV2Params struct {
	// Size Maximum number of results to return (maximum 5 000).
	Size CredentialsFeedSize `form:"size,omitempty" json:"size,omitempty,omitzero"`

	// From The next value from the last response.
	From From `form:"from,omitempty" json:"from,omitempty,omitzero"`

	// Order Browse order. Defaults to asc, which is recommended for fetching newly imported passwords.
	Order FeedOrder `form:"order,omitempty" json:"order,omitempty,omitzero"`

	// SourceID Return only credentials that belong to this source.
	SourceID SourceID `form:"source_id,omitempty" json:"source_id,omitempty,omitzero"`
}

// ListByBulkAccountsJSONRequestBody defines body for ListByBulkAccounts for application/json ContentType.
type ListByBulkAccountsJSONRequestBody = ByAccountsRequest

// ListURLsByCredentialHashJSONRequestBody defines body for ListURLsByCredentialHash for application/json ContentType.
type ListURLsByCredentialHashJSONRequestBody = URLsByCredentialHashRequest

// SearchCookiesJSONRequestBody defines body for SearchCookies for application/json ContentType.
type SearchCookiesJSONRequestBody = CookiesSearchRequest

// SearchCredentialsJSONRequestBody defines body for SearchCredentials for application/json ContentType.
type SearchCredentialsJSONRequestBody = CredentialsSearchRequest

// Getter for additional properties for IdentityLinks. Returns the specified
// element and whether it was found
func (a IdentityLinks) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for IdentityLinks
func (a *IdentityLinks) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for IdentityLinks to handle AdditionalProperties
func (a *IdentityLinks) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["next"]; found {
		err = json.Unmarshal(raw, &a.Next)
		if err != nil {
			return fmt.Errorf("error reading 'next': %w", err)
		}
		delete(object, "next")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for IdentityLinks to handle AdditionalProperties
func (a IdentityLinks) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["next"], err = json.Marshal(a.Next)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'next': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsDomainQuery returns the union data inside the CredentialsQuery as a DomainQuery
func (t CredentialsQuery) AsDomainQuery() (DomainQuery, error) {
	var body DomainQuery
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDomainQuery overwrites any union data inside the CredentialsQuery as the provided DomainQuery
func (t *CredentialsQuery) FromDomainQuery(v DomainQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"domain"}`))
	t.union = b
	return err
}

// MergeDomainQuery performs a merge with any union data inside the CredentialsQuery, using the provided DomainQuery
func (t *CredentialsQuery) MergeDomainQuery(v DomainQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"domain"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAuthDomainQuery returns the union data inside the CredentialsQuery as a AuthDomainQuery
func (t CredentialsQuery) AsAuthDomainQuery() (AuthDomainQuery, error) {
	var body AuthDomainQuery
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuthDomainQuery overwrites any union data inside the CredentialsQuery as the provided AuthDomainQuery
func (t *CredentialsQuery) FromAuthDomainQuery(v AuthDomainQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"auth_domain"}`))
	t.union = b
	return err
}

// MergeAuthDomainQuery performs a merge with any union data inside the CredentialsQuery, using the provided AuthDomainQuery
func (t *CredentialsQuery) MergeAuthDomainQuery(v AuthDomainQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"auth_domain"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSecretQuery returns the union data inside the CredentialsQuery as a SecretQuery
func (t CredentialsQuery) AsSecretQuery() (SecretQuery, error) {
	var body SecretQuery
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecretQuery overwrites any union data inside the CredentialsQuery as the provided SecretQuery
func (t *CredentialsQuery) FromSecretQuery(v SecretQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"secret"}`))
	t.union = b
	return err
}

// MergeSecretQuery performs a merge with any union data inside the CredentialsQuery, using the provided SecretQuery
func (t *CredentialsQuery) MergeSecretQuery(v SecretQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"secret"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailQuery returns the union data inside the CredentialsQuery as a EmailQuery
func (t CredentialsQuery) AsEmailQuery() (EmailQuery, error) {
	var body EmailQuery
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailQuery overwrites any union data inside the CredentialsQuery as the provided EmailQuery
func (t *CredentialsQuery) FromEmailQuery(v EmailQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"email"}`))
	t.union = b
	return err
}

// MergeEmailQuery performs a merge with any union data inside the CredentialsQuery, using the provided EmailQuery
func (t *CredentialsQuery) MergeEmailQuery(v EmailQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"email"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsKeywordQuery returns the union data inside the CredentialsQuery as a KeywordQuery
func (t CredentialsQuery) AsKeywordQuery() (KeywordQuery, error) {
	var body KeywordQuery
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromKeywordQuery overwrites any union data inside the CredentialsQuery as the provided KeywordQuery
func (t *CredentialsQuery) FromKeywordQuery(v KeywordQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"keyword"}`))
	t.union = b
	return err
}

// MergeKeywordQuery performs a merge with any union data inside the CredentialsQuery, using the provided KeywordQuery
func (t *CredentialsQuery) MergeKeywordQuery(v KeywordQuery) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"keyword"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CredentialsQuery) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CredentialsQuery) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "auth_domain":
		return t.AsAuthDomainQuery()
	case "domain":
		return t.AsDomainQuery()
	case "email":
		return t.AsEmailQuery()
	case "keyword":
		return t.AsKeywordQuery()
	case "secret":
		return t.AsSecretQuery()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CredentialsQuery) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CredentialsQuery) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
