version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    gosec:
      excludes:
        - G306
    staticcheck:
      checks:
        - -S1028
        - all
        - -QF1002
#        - -S1034
#        - -QF1001
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
