// Package tokens provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tokens

// TokenGenerateRequest defines model for TokenGenerateRequest.
type TokenGenerateRequest struct {
	// TenantID The tenant you want to authenticate to. When unspecified, the API token is generated for your default tenant.
	TenantID int `json:"tenant_id,omitempty,omitzero"`
}

// TokenGenerateResponse defines model for TokenGenerateResponse.
type TokenGenerateResponse struct {
	// RefreshTokenExp Unix timestamp of the expiration of the refresh token, which is returned in cookies. This is not the API token's expiry.
	RefreshTokenExp int64 `json:"refresh_token_exp"`

	// Token The generated API token. It expires after 1 hour.
	Token string `json:"token"`
}

// TokenTestResponse defines model for TokenTestResponse.
type TokenTestResponse struct {
	// APIKeyID The ID of the API key that was used to generate this token.
	APIKeyID       int      `json:"api_key_id,omitempty,omitzero"`
	OrganizationID int      `json:"organization_id,omitempty,omitzero"`
	Scopes         []string `json:"scopes,omitempty,omitzero"`

	// TenantID The currently authenticated tenant ID.
	TenantID  int    `json:"tenant_id,omitempty,omitzero"`
	UserEmail string `json:"user_email,omitempty,omitzero"`
	UserID    int    `json:"user_id,omitempty,omitzero"`
}

// GenerateTokenParams defines parameters for GenerateToken.
type GenerateTokenParams struct {
	// Authorization Your Flare API key.
	Authorization string `json:"Authorization"`
}

// GenerateTokenJSONRequestBody defines body for GenerateToken for application/json ContentType.
type GenerateTokenJSONRequestBody = TokenGenerateRequest
