package phlare

import (
	"time"

	"github.com/mr-pmillz/gophlare/flareapi/astp"
	"github.com/mr-pmillz/gophlare/flareapi/fireworkv2"
	"github.com/mr-pmillz/gophlare/flareapi/fireworkv4"
	"github.com/mr-pmillz/gophlare/flareapi/tokens"
	"github.com/mr-pmillz/gophlare/metrics"
)

// FlareClient ...
type FlareClient struct {
	APIKey           string
	TenantID         int
	Client           *Client
	DefaultUserAgent string
	Token            *string
	TokenExp         *time.Time
	ClientTimeout    int
	// BaseURL is the Flare API root. Defaults to flareAPIBaseURL; override via
	// WithBaseURL, which is what makes this client testable against httptest.
	BaseURL string
	// Metrics accumulates API usage for the --metrics report. Nil disables
	// recording, so SDK consumers who never opt in pay nothing.
	Metrics *metrics.Recorder
	// Entity attributes requests that carry no domain parameter (activity
	// retrieval, file downloads) to a target. Set via ForEntity.
	Entity string
	// GlobalSearchPageSize is the `size` sent to the global events search.
	// Defaults to DefaultGlobalSearchPageSize.
	GlobalSearchPageSize int
}

// The Flare API request and response types below alias models generated by
// oapi-codegen into the flareapi packages, keeping gophlare's established
// names. See flareapi/openapi for the specs they are generated from.

// FlareAuthResponse is the /tokens/generate response.
type FlareAuthResponse = tokens.TokenGenerateResponse

// FlareSearchCredentialsBodyParams is the /astp/v2/credentials/_search request body.
type FlareSearchCredentialsBodyParams = astp.CredentialsSearchRequest

// FlareDomainQuery is the domain query of FlareSearchCredentialsBodyParams.
// Set it with FlareSearchCredentialsBodyParams.Query.FromDomainQuery.
type FlareDomainQuery = astp.DomainQuery

// FlareSearchCredentialsASTP is the /astp/v2/credentials/_search response.
type FlareSearchCredentialsASTP = astp.CredentialsSearchResponse

// FlareSearchCredentials is the /leaksdb/v2/credentials response.
//
// Deprecated: Flare deprecated /leaksdb/v2/credentials in favour of
// /astp/v2/credentials/_search; use FlareSearchCredentialsASTP.
type FlareSearchCredentials = astp.CredentialsV2Response

// FlareSearchCookiesBodyParams is the /astp/v2/cookies/_search request body.
type FlareSearchCookiesBodyParams = astp.CookiesSearchRequest

// FlareSearchCookiesResponse is the /astp/v2/cookies/_search response.
type FlareSearchCookiesResponse = astp.CookiesSearchResponse

// FlareEventsGlobalSearchBodyParams is the /firework/v4/events/global/_search request body.
type FlareEventsGlobalSearchBodyParams = fireworkv4.GlobalSearchRequestBody

// Query is the query_string query of FlareEventsGlobalSearchBodyParams.
// Set it with FlareEventsGlobalSearchBodyParams.Query.FromQueryStringQuery.
type Query = fireworkv4.QueryStringQuery

// Filters holds the filters of FlareEventsGlobalSearchBodyParams.
type Filters = fireworkv4.FeedFilters

// EstimatedCreatedAt is the date range filter used by Filters.
type EstimatedCreatedAt = fireworkv4.DateFilter

// FlareEventsGlobalSearchResults is the /firework/v4/events/global/_search response.
type FlareEventsGlobalSearchResults = fireworkv4.PaginatedResultsGlobalFeedItemStr

// FlareStealerLogZipFileDownloadResponse is the undocumented
// /firework/v2/activities/{uid}/download response.
type FlareStealerLogZipFileDownloadResponse = fireworkv2.StealerLogDownloadResponse

// FlareFireworkActivitiesIndexSourceIDv2Response is the /firework/v2/activities/
// response for a stealer_log event.
type FlareFireworkActivitiesIndexSourceIDv2Response = fireworkv2.StealerLogActivityResponse

// FlareListByBulkAccountResponse is the /astp/identities/by_accounts response,
// keyed by account name.
type FlareListByBulkAccountResponse = astp.ByAccountsResponse

// Entry is the identity returned for each account in FlareListByBulkAccountResponse.
type Entry = astp.Identity

// Password is one breached credential of an Entry.
type Password = astp.IdentityPassword

// Source is the breach source of a Password.
type Source = astp.LeakSource

// FlareStealerLogsCredential holds the parsed information for each entry
type FlareStealerLogsCredential struct {
	Software string
	URL      string
	Username string
	Password string
}

// Cookie ...
type Cookie struct {
	Domain         string
	Secure         bool
	Path           string
	HTTPOnly       bool
	Expiration     int64
	IsExpired      bool
	ExpirationDate string
	Name           string
	Value          string
}

// CookieBro ...
type CookieBro struct {
	Name             string `json:"name,omitempty"`
	Value            string `json:"value,omitempty"`
	Domain           string `json:"domain,omitempty"`
	HostOnly         bool   `json:"hostOnly,omitempty"`
	Path             string `json:"path,omitempty"`
	Secure           bool   `json:"secure,omitempty"`
	HTTPOnly         bool   `json:"httpOnly,omitempty"`
	SameSite         string `json:"sameSite,omitempty"`
	Session          bool   `json:"session,omitempty"`
	FirstPartyDomain string `json:"firstPartyDomain,omitempty"`
	PartitionKey     any    `json:"partitionKey,omitempty"`
	ExpirationDate   int64  `json:"expirationDate,omitempty"`
	StoreID          string `json:"storeId,omitempty"`
}
