// Package fireworkv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fireworkv2

import "github.com/mr-pmillz/gophlare/flareapi/flaretime"

// StealerLogActivity defines model for StealerLogActivity.
type StealerLogActivity struct {
	Data         StealerLogData     `json:"data,omitempty,omitzero"`
	Duplicates   []interface{}      `json:"duplicates,omitempty,omitzero"`
	Header       StealerLogHeader   `json:"header,omitempty,omitzero"`
	HistoryLogs  interface{}        `json:"history_logs,omitempty,omitzero"`
	Metadata     StealerLogMetadata `json:"metadata,omitempty,omitzero"`
	SimilarItems []interface{}      `json:"similar_items,omitempty,omitzero"`
}

// StealerLogActivityResponse The GET /firework/v2/activities/ response for a stealer_log (also indexed as bot) event.
type StealerLogActivityResponse struct {
	Activity StealerLogActivity `json:"activity,omitempty,omitzero"`
}

// StealerLogCookie defines model for StealerLogCookie.
type StealerLogCookie struct {
	// ExpiresUtc Expiry as a timezone-less UTC timestamp, for example 2026-03-04T02:22:08.
	ExpiresUtc string `json:"expires_utc,omitempty,omitzero"`
	HostKey    string `json:"host_key,omitempty,omitzero"`
	Name       string `json:"name,omitempty,omitzero"`
	Path       string `json:"path,omitempty,omitzero"`
	Value      string `json:"value,omitempty,omitzero"`
}

// StealerLogCredential defines model for StealerLogCredential.
type StealerLogCredential struct {
	Application string `json:"application,omitempty,omitzero"`

	// Password Usually partially redacted.
	Password string `json:"password,omitempty,omitzero"`
	URL      string `json:"url,omitempty,omitzero"`
	Username string `json:"username,omitempty,omitzero"`
}

// StealerLogData defines model for StealerLogData.
type StealerLogData struct {
	BrowserURL  interface{}            `json:"browser_url,omitempty,omitzero"`
	Cookies     []StealerLogCookie     `json:"cookies,omitempty,omitzero"`
	Credentials []StealerLogCredential `json:"credentials,omitempty,omitzero"`
	Currency    interface{}            `json:"currency,omitempty,omitzero"`
	EsID        string                 `json:"es_id,omitempty,omitzero"`
	EsScore     interface{}            `json:"es_score,omitempty,omitzero"`
	Features    StealerLogFeatures     `json:"features,omitempty,omitzero"`

	// Files Paths of the files in the stealer log archive.
	Files              []string                     `json:"files,omitempty,omitzero"`
	Highlights         map[string]interface{}       `json:"highlights,omitempty,omitzero"`
	ID                 string                       `json:"id,omitempty,omitzero"`
	Index              string                       `json:"index,omitempty,omitzero"`
	Information        interface{}                  `json:"information,omitempty,omitzero"`
	InstalledAt        flaretime.Time               `json:"installed_at,omitempty,omitzero"`
	Isp                interface{}                  `json:"isp,omitempty,omitzero"`
	MalwareInformation StealerLogMalwareInformation `json:"malware_information,omitempty,omitzero"`
	Metadata           StealerLogMetadata           `json:"metadata,omitempty,omitzero"`
	Name               interface{}                  `json:"name,omitempty,omitzero"`
	Price              interface{}                  `json:"price,omitempty,omitzero"`

	// Resources Sometimes holds credentials formatted as "Host: URL | Username: EMAIL | Password: PASSWORD".
	Resources       []string                  `json:"resources,omitempty,omitzero"`
	SellerID        interface{}               `json:"seller_id,omitempty,omitzero"`
	Sources         []string                  `json:"sources,omitempty,omitzero"`
	UID             string                    `json:"uid,omitempty,omitzero"`
	UpdatedAt       interface{}               `json:"updated_at,omitempty,omitzero"`
	URL             interface{}               `json:"url,omitempty,omitzero"`
	UserInformation StealerLogUserInformation `json:"user_information,omitempty,omitzero"`
}

// StealerLogDownloadResponse defines model for StealerLogDownloadResponse.
type StealerLogDownloadResponse struct {
	StealerLog struct {
		// ExternalURL Short-lived URL of the stealer log's zip archive.
		ExternalURL string `json:"external_url,omitempty,omitzero"`
	} `json:"stealer_log,omitempty,omitzero"`
}

// StealerLogFeatures defines model for StealerLogFeatures.
type StealerLogFeatures struct {
	Domains         []string    `json:"domains,omitempty,omitzero"`
	Emails          []string    `json:"emails,omitempty,omitzero"`
	IPAddresses     []string    `json:"ip_addresses,omitempty,omitzero"`
	IPAddressesCidr []string    `json:"ip_addresses_cidr,omitempty,omitzero"`
	ReversedDomains []string    `json:"reversed_domains,omitempty,omitzero"`
	Urls            []string    `json:"urls,omitempty,omitzero"`
	Usernames       []string    `json:"usernames,omitempty,omitzero"`
	Vulnerabilities interface{} `json:"vulnerabilities,omitempty,omitzero"`
}

// StealerLogHeader defines model for StealerLogHeader.
type StealerLogHeader struct {
	Actor                     interface{}            `json:"actor,omitempty,omitzero"`
	ActorID                   interface{}            `json:"actor_id,omitempty,omitzero"`
	AnalyzersItemsUids        []interface{}          `json:"analyzers_items_uids,omitempty,omitzero"`
	Bank                      interface{}            `json:"bank,omitempty,omitzero"`
	Bin                       interface{}            `json:"bin,omitempty,omitzero"`
	Brand                     interface{}            `json:"brand,omitempty,omitzero"`
	CanHaveDuplicates         bool                   `json:"can_have_duplicates,omitempty,omitzero"`
	CategoryName              string                 `json:"category_name,omitempty,omitzero"`
	ContainsSecrets           interface{}            `json:"contains_secrets,omitempty,omitzero"`
	ContentHash               string                 `json:"content_hash,omitempty,omitzero"`
	ContentPreview            string                 `json:"content_preview,omitempty,omitzero"`
	Country                   interface{}            `json:"country,omitempty,omitzero"`
	CredentialCount           int                    `json:"credential_count,omitempty,omitzero"`
	Duplicates                []interface{}          `json:"duplicates,omitempty,omitzero"`
	EsScore                   interface{}            `json:"es_score,omitempty,omitzero"`
	Expiration                interface{}            `json:"expiration,omitempty,omitzero"`
	ExternalNetloc            string                 `json:"external_netloc,omitempty,omitzero"`
	ExternalURL               string                 `json:"external_url,omitempty,omitzero"`
	Highlights                map[string]interface{} `json:"highlights,omitempty,omitzero"`
	Host                      interface{}            `json:"host,omitempty,omitzero"`
	ID                        string                 `json:"id,omitempty,omitzero"`
	IgnoredAt                 interface{}            `json:"ignored_at,omitempty,omitzero"`
	InfectionDate             flaretime.Time         `json:"infection_date,omitempty,omitzero"`
	Notes                     interface{}            `json:"notes,omitempty,omitzero"`
	ParentID                  interface{}            `json:"parent_id,omitempty,omitzero"`
	ParentTitle               interface{}            `json:"parent_title,omitempty,omitzero"`
	ParentTitleEn             interface{}            `json:"parent_title_en,omitempty,omitzero"`
	ParentUID                 interface{}            `json:"parent_uid,omitempty,omitzero"`
	ParentUids                []string               `json:"parent_uids,omitempty,omitzero"`
	PriorityActionUUIDRelated bool                   `json:"priority_action_uuid_related,omitempty,omitzero"`
	RemediatedAt              interface{}            `json:"remediated_at,omitempty,omitzero"`
	Risk                      StealerLogRisk         `json:"risk,omitempty,omitzero"`
	SecretsMetadata           interface{}            `json:"secrets_metadata,omitempty,omitzero"`
	SimilarItemsCount         int                    `json:"similar_items_count,omitempty,omitzero"`
	Source                    string                 `json:"source,omitempty,omitzero"`
	SourceName                string                 `json:"source_name,omitempty,omitzero"`
	StateCode                 interface{}            `json:"state_code,omitempty,omitzero"`
	Tags                      []interface{}          `json:"tags,omitempty,omitzero"`
	TargetName                string                 `json:"target_name,omitempty,omitzero"`
	Timestamp                 flaretime.Time         `json:"timestamp,omitempty,omitzero"`
	Title                     string                 `json:"title,omitempty,omitzero"`
	Type                      string                 `json:"type,omitempty,omitzero"`
	UID                       string                 `json:"uid,omitempty,omitzero"`
	UserNotes                 interface{}            `json:"user_notes,omitempty,omitzero"`
	UserRiskScore             interface{}            `json:"user_risk_score,omitempty,omitzero"`
	Verb                      string                 `json:"verb,omitempty,omitzero"`
	VictimName                interface{}            `json:"victim_name,omitempty,omitzero"`
}

// StealerLogMalwareInformation defines model for StealerLogMalwareInformation.
type StealerLogMalwareInformation struct {
	BuildID       string         `json:"build_id,omitempty,omitzero"`
	FileLocation  string         `json:"file_location,omitempty,omitzero"`
	InfectionDate flaretime.Time `json:"infection_date,omitempty,omitzero"`
	MalwareFamily string         `json:"malware_family,omitempty,omitzero"`
}

// StealerLogMetadata defines model for StealerLogMetadata.
type StealerLogMetadata struct {
	CrawledBy          interface{}    `json:"crawled_by,omitempty,omitzero"`
	EstimatedCreatedAt flaretime.Time `json:"estimated_created_at,omitempty,omitzero"`
	EventID            interface{}    `json:"event_id,omitempty,omitzero"`
	FirstCrawledAt     flaretime.Time `json:"first_crawled_at,omitempty,omitzero"`
	FlareURL           string         `json:"flare_url,omitempty,omitzero"`
	LastCrawledAt      flaretime.Time `json:"last_crawled_at,omitempty,omitzero"`
	PayloadDigest      string         `json:"payload_digest,omitempty,omitzero"`
	ScrapedAt          flaretime.Time `json:"scraped_at,omitempty,omitzero"`
	Source             string         `json:"source,omitempty,omitzero"`
}

// StealerLogRisk defines model for StealerLogRisk.
type StealerLogRisk struct {
	Score int `json:"score,omitempty,omitzero"`
}

// StealerLogUserInformation defines model for StealerLogUserInformation.
type StealerLogUserInformation struct {
	AntiViruses        interface{} `json:"anti_viruses,omitempty,omitzero"`
	AvailableKeyboards []string    `json:"available_keyboards,omitempty,omitzero"`
	CountryCode        string      `json:"country_code,omitempty,omitzero"`
	CurrentLanguage    string      `json:"current_language,omitempty,omitzero"`
	Hardware           []string    `json:"hardware,omitempty,omitzero"`
	Hwid               string      `json:"hwid,omitempty,omitzero"`
	IPAddress          string      `json:"ip_address,omitempty,omitzero"`
	IPNetwork          interface{} `json:"ip_network,omitempty,omitzero"`
	Location           string      `json:"location,omitempty,omitzero"`
	Os                 string      `json:"os,omitempty,omitzero"`
	ProcessElevation   interface{} `json:"process_elevation,omitempty,omitzero"`
	ScreensizeHeight   int         `json:"screensize_height,omitempty,omitzero"`
	ScreensizeWidth    int         `json:"screensize_width,omitempty,omitzero"`
	Timezone           string      `json:"timezone,omitempty,omitzero"`
	Uac                string      `json:"uac,omitempty,omitzero"`
	Username           string      `json:"username,omitempty,omitzero"`
	ZipCode            string      `json:"zip_code,omitempty,omitzero"`
}

// AgreeToTOS defines model for AgreeToTOS.
type AgreeToTOS = bool

// UID defines model for UID.
type UID = string

// DownloadStealerLogParams defines parameters for DownloadStealerLog.
type DownloadStealerLogParams struct {
	IAgreeToTos AgreeToTOS `form:"i_agree_to_tos" json:"i_agree_to_tos"`
}

// DownloadStealerLogFileParams defines parameters for DownloadStealerLogFile.
type DownloadStealerLogFileParams struct {
	IAgreeToTos AgreeToTOS `form:"i_agree_to_tos" json:"i_agree_to_tos"`

	// File A path from the stealer log's files list.
	File string `form:"file" json:"file"`
}
